/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Healthz
         * @description Liveness — the process is up.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readyz
         * @description Readiness — the database answers.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dictionary/{lang}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Dictionary
         * @description The whole dictionary for a language (what loadVocab fetches).
         */
        get: operations["get_dictionary_v1_dictionary__lang__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dictionary/{lang}/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Entry
         * @description A single entry by its slug.
         */
        get: operations["get_entry_v1_dictionary__lang___slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Bridge */
        Bridge: {
            /** Kanji */
            kanji: string;
            /** Kana */
            kana?: string | null;
            /** Rr */
            rr: string;
            /** Kind */
            kind: string;
        };
        /** DictionaryEntryOut */
        DictionaryEntryOut: {
            /** Id */
            id: string;
            /** Head */
            head: string;
            /** Hanja */
            hanja?: string | null;
            reading: components["schemas"]["Reading"];
            /** Pos */
            pos: string;
            /** Origin */
            origin: string;
            /** En */
            en: string;
            /** Senses */
            senses: components["schemas"]["Sense"][];
            /** Band */
            band?: number | null;
            /** Freqrank */
            freqRank?: number | null;
            /** Conjugation */
            conjugation?: string | null;
            /** Domain */
            domain?: string | null;
            /** Grade */
            grade?: string | null;
            bridge?: components["schemas"]["Bridge"] | null;
            ex?: components["schemas"]["Example"] | null;
            note?: components["schemas"]["Note"] | null;
            /** Source */
            source: string;
            /** Krdictid */
            krdictId?: string | null;
        };
        /**
         * DictionarySlice
         * @description A whole language's dictionary — what loadVocab(lang) returns.
         */
        DictionarySlice: {
            /** Lang */
            lang: string;
            /** Count */
            count: number;
            /** Entries */
            entries: components["schemas"]["DictionaryEntryOut"][];
        };
        /** Example */
        Example: {
            /** Text */
            text: string;
            /** Rr */
            rr?: string | null;
            /** Jp */
            jp?: string | null;
            /** Jprr */
            jpRr?: string | null;
            /** En */
            en?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Note */
        Note: {
            /** Head */
            head: string;
            /** Html */
            html: string;
        };
        /** Reading */
        Reading: {
            /** Rr */
            rr: string;
            /** Kana */
            kana?: string | null;
        };
        /** Sense */
        Sense: {
            /** Gloss */
            gloss: string;
            /** Def */
            def?: string | null;
            /** Endef */
            enDef?: string | null;
            /** Domain */
            domain?: string | null;
            note?: components["schemas"]["Note"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_dictionary_v1_dictionary__lang__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lang: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionarySlice"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entry_v1_dictionary__lang___slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lang: string;
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DictionaryEntryOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
